# Generated by Django 2.0.3 on 2018-03-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=200)),
                ('create_date', models.DateField(auto_now=True)),
                ('intro', models.TextField(max_length=200)),
                ('down_link', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
